import { ComicDetails } from "dh-marvel/components/comicDetails/ComicDetails";
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { Comics } from "dh-marvel/features/marvel/comics.type";
import { getComic, getComics } from "dh-marvel/services/marvel/marvel.service";
import { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import React from "react";
/**En esta página se deberá mostrar un detalle de un cómic seleccionado junto al precio y stock del mismo. 

Se deberá tener en cuenta lo siguiente:
* Deberá estar en la ruta `/comics/[id]`.
* La página deberá indicar al menos la siguiente información:
  * Nombre del comic
  * Descripción del comic
  * Imagen principal
  * Precio
  * Precio anterior
  * Botón de compra: en función de la disponibilidad de stock
    * Si hay stock, el botón debe aparecer habilitado y ser funcional
    * Si no hay stock, el botón debe estar deshabilitado y en gris, con el mensaje: Sin stock disponible 
  * Lista de personajes asociados al cómic, con links a la página de cada personaje
* Permitir que el contenido sea indexable por los buscadores.
* Esta página debera utilizar el [Layout General](#layout-general) */

interface PropsComic {
  comicApi: Comics;
}

const ComicPage: NextPage<PropsComic> = ({ comicApi }) => {
  return (
    <>
      <Head>
        <title>DH-Marvel Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BodySingle title={"Comic details:"}>
        <ComicDetails {...comicApi} />
      </BodySingle>
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const id = Number(params?.id);
  try {
    const comicApi = await getComic(id);

    return {
      props: {
        comicApi,
      },
      revalidate: 10,
    };
  } catch (error) {
    console.error("No se pudo obtener el personaje", error);
    return {
      props: {
        comic: {},
      },
    };
  }
};

export const getStaticPaths: GetStaticPaths = async () => {
  const res = await getComics();
  const comics = res?.data?.results || [];
  const paths = comics.map((comic: Comics) => ({
    params: { id: comic.id.toString() },
  }));
  return { paths, fallback: false };
};

export default ComicPage;
