import { ComicDetails } from "dh-marvel/components/comicDetails/ComicDetails";
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { Comics } from "dh-marvel/features/marvel/comics.type";
import { getComic, getComics } from "dh-marvel/services/marvel/marvel.service";
import { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import React from "react";
interface PropsComic {
  comicApi: Comics;
}

const ComicPage: NextPage<PropsComic> = ({ comicApi }) => {
  return (
    <>
      <Head>
        <title>Dh-Marvel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BodySingle title={"Comic details:"}>
        <ComicDetails {...comicApi} />
      </BodySingle>
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const id = Number(params?.id);
  try {
    const comicApi = await getComic(id);

    return {
      props: {
        comicApi,
      },
      revalidate: 10,
    };
  } catch (error) {
    return {
      props: {
        comic: {},
      },
    };
  }
};

export const getStaticPaths: GetStaticPaths = async () => {
  const res = await getComics();
  const comics = res?.data?.results || [];
  const paths = comics.map((comic: Comics) => ({
    params: { id: comic.id.toString() },
  }));
  return { paths, fallback: false };
};

export default ComicPage;
