import OrderDetail from "dh-marvel/components/confirmacionCompra/OrderDetail";
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import LayoutCheckout from "dh-marvel/components/layouts/layout-checkout";
import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

const ConfirmationOrder: NextPage = () => {
  const router = useRouter();
  const { comicName, comicPrice, comicImage, address } = router.query;
  const handleClickGoHome = () => {
    router.push("/");
  };

  return (
    <LayoutCheckout>
      <Head>
        <title>Dh-Marvel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BodySingle title="Confirmacion de compra:">
        <OrderDetail
          comicName={(comicName as string) || ""}
          comicImage={(comicImage as string) || ""}
          address={(address as string) || ""}
          price={(comicPrice as string) || ""}
          onGoBackClick={handleClickGoHome}
        />
      </BodySingle>
    </LayoutCheckout>
  );
};

export default ConfirmationOrder;
